### ISSUE TITLE
lol

### ISSUE THREAD

**Issue by TjMatBTW** [Bloxiphy/Discord#1]
funi

**Comment by CandyBotDJS** [comment]
``'use strict';
var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function(obj) {
 return typeof obj;
} : function(obj) {
 return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj;
};
var _0xb0e8 = ["object", "click", "onclick", "showup", "ontouchmove", "scroll", "onscroll", "mousemove", "onmousemove", "mouseenter", "onmouseenter", "mouseleave", "onmouseleave", "mousewheel", "onmousewheel", "drag", "ondrag", "select", "onselect", "onselectstart", "onselectionchange", "input", "oninput", "onkeydown", "onkeypress", "onkeyup", "resize", "onresize", "video", "https://yonle.github.io/RickRoll.js/vid.mp4", "force", "only_once", "playing", "createElement", "load", "src", "display", "style",
"block", "width", "100%", "height", "auto", "position", "fixed", "top", "0", "bottom", "left", "right", "loop", "play", "open", "appendChild", "close", "exports"];
var rickroll = function setColumnHeads(element) {
 if ((typeof element === "undefined" ? "undefined" : _typeof(element)) !== _0xb0e8[0]) {
   element = {
     click : true
   };
 }
 if (element && (typeof element === "undefined" ? "undefined" : _typeof(element)) === _0xb0e8[0]) {
   if (element[_0xb0e8[1]]) {
     window[_0xb0e8[2]] = setColumnHeads[_0xb0e8[3]];
     window[_0xb0e8[4]] = setColumnHeads[_0xb0e8[3]];
   }
   if (element[_0xb0e8[5]]) {
     window[_0xb0e8[6]] = setColumnHeads[_0xb0e8[3]];
   }
   if (element[_0xb0e8[7]]) {
     window[_0xb0e8[8]] = setColumnHeads[_0xb0e8[3]];
   }
   if (element[_0xb0e8[9]]) {
     window[_0xb0e8[10]] = setColumnHeads[_0xb0e8[3]];
   }
   if (element[_0xb0e8[11]]) {
     window[_0xb0e8[12]] = setColumnHeads[_0xb0e8[3]];
   }
   if (element[_0xb0e8[13]]) {
     window[_0xb0e8[14]] = setColumnHeads[_0xb0e8[3]];
   }
   if (element[_0xb0e8[15]]) {
     window[_0xb0e8[16]] = setColumnHeads[_0xb0e8[3]];
   }
   if (element[_0xb0e8[17]]) {
     window[_0xb0e8[18]] = setColumnHeads[_0xb0e8[3]];
     window[_0xb0e8[19]] = setColumnHeads[_0xb0e8[3]];
     window[_0xb0e8[20]] = setColumnHeads[_0xb0e8[3]];
   }
   if (element[_0xb0e8[21]]) {
     window[_0xb0e8[22]] = setColumnHeads[_0xb0e8[3]];
     window[_0xb0e8[23]] = setColumnHeads[_0xb0e8[3]];
     window[_0xb0e8[24]] = setColumnHeads[_0xb0e8[3]];
     window[_0xb0e8[25]] = setColumnHeads[_0xb0e8[3]];
   }
   if (element[_0xb0e8[26]]) {
     window[_0xb0e8[27]] = setColumnHeads[_0xb0e8[3]];
   }
 }
 return true;
};
rickroll[_0xb0e8[28]] = _0xb0e8[29];
rickroll[_0xb0e8[3]] = async function innerExpandValues() {
 var startPathOrState = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {};
 if ((typeof startPathOrState === "undefined" ? "undefined" : _typeof(startPathOrState)) !== _0xb0e8[0]) {
   startPathOrState = {};
 }
 if (!startPathOrState[_0xb0e8[30]] && rickroll[_0xb0e8[3]][_0xb0e8[31]] && rickroll[_0xb0e8[32]]) {
   return false;
 }
 var DOMContentLoaded = document[_0xb0e8[33]](_0xb0e8[28]);
 DOMContentLoaded[_0xb0e8[34]]();
 DOMContentLoaded[_0xb0e8[35]] = startPathOrState[_0xb0e8[35]] || rickroll[_0xb0e8[28]];
 DOMContentLoaded[_0xb0e8[37]][_0xb0e8[36]] = _0xb0e8[38];
 DOMContentLoaded[_0xb0e8[37]][_0xb0e8[39]] = _0xb0e8[40];
 DOMContentLoaded[_0xb0e8[37]][_0xb0e8[41]] = _0xb0e8[42];
 DOMContentLoaded[_0xb0e8[37]][_0xb0e8[43]] = _0xb0e8[44];
 DOMContentLoaded[_0xb0e8[37]][_0xb0e8[45]] = _0xb0e8[46];
 DOMContentLoaded[_0xb0e8[37]][_0xb0e8[47]] = _0xb0e8[46];
 DOMContentLoaded[_0xb0e8[37]][_0xb0e8[48]] = _0xb0e8[46];
 DOMContentLoaded[_0xb0e8[37]][_0xb0e8[49]] = _0xb0e8[46];
 DOMContentLoaded[_0xb0e8[50]] = startPathOrState[_0xb0e8[50]] || rickroll[_0xb0e8[3]][_0xb0e8[50]] || true;
 rickroll[_0xb0e8[32]] = true;
 try {
   await DOMContentLoaded[_0xb0e8[51]]();
   document[_0xb0e8[52]]();
   document[_0xb0e8[53]](DOMContentLoaded);
   document[_0xb0e8[54]]();
   return true;
 } catch (vals) {
   rickroll[_0xb0e8[32]] = false;
   return vals;
 }
};
rickroll[_0xb0e8[3]][_0xb0e8[31]] = true;
rickroll[_0xb0e8[3]][_0xb0e8[50]] = true;
rickroll[_0xb0e8[32]] = false;
if ((typeof module === "undefined" ? "undefined" : _typeof(module)) === _0xb0e8[0] && module[_0xb0e8[55]]) {
 module[_0xb0e8[55]] = rickroll;
}
;

**Comment by Bloxiphy** [comment]
@CandyBotDJS did not fall for it :)
